server:
  port: 8087
  error:
    include-messages: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/tqi/tqi-backend-db
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
